# Generated by Django 3.0.7 on 2020-07-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='mention',
            field=models.ManyToManyField(to='query.Users'),
        ),
        migrations.AlterField(
            model_name='results',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='query.Users'),
        ),
        migrations.DeleteModel(
            name='Mentions',
        ),
    ]
